//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Övning_5_Resources.PropertyMapping {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PropertyToRegExp {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PropertyToRegExp() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Övning_5_Resources.PropertyMapping.PropertyToRegExp", typeof(PropertyToRegExp).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^([1-9][0-9]?)$|^(1[0-2][0-8])$.
        /// </summary>
        internal static string Capacity {
            get {
                return ResourceManager.GetString("Capacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^(?i:GASOLINE|DIESEL)$.
        /// </summary>
        internal static string FuelType {
            get {
                return ResourceManager.GetString("FuelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^[a-zA-Z]{3}\d{3}$.
        /// </summary>
        internal static string LicensePlate {
            get {
                return ResourceManager.GetString("LicensePlate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^[1-2]$.
        /// </summary>
        internal static string NumberOfAttributes {
            get {
                return ResourceManager.GetString("NumberOfAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^([1-9])$|^([1-5][0-9]?)$|^(6[0-4])$.
        /// </summary>
        internal static string NumberOfEngines {
            get {
                return ResourceManager.GetString("NumberOfEngines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^([0-9][0-9]?)$|^([1-4][0-9][0-9])$|^(50[0-9])$|^(51[0-2])$.
        /// </summary>
        internal static string NumberOfParachutes {
            get {
                return ResourceManager.GetString("NumberOfParachutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^([1-9][0-9]?)$|^([1-4][0-9][0-9])$|^(50[0-9])$|^(51[0-2])$.
        /// </summary>
        internal static string NumberOfSeats {
            get {
                return ResourceManager.GetString("NumberOfSeats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^(?i:FALSE|TRUE)$.
        /// </summary>
        internal static string Silencer {
            get {
                return ResourceManager.GetString("Silencer", resourceCulture);
            }
        }
    }
}
